### ISSUE TITLE
Criar rota getAll eventos

### ISSUE THREAD

**Issue by mhme2000** [ViniciusLuisZ/projetoSi#28]
Adicionar estrutura controller-service-repository para a listagem de eventos enviados.

Segue imagem da listagem abaixo:
![image](https://user-images.githubusercontent.com/45264849/175427008-db468de4-527c-4784-9e2a-fd19fd1915bf.png)
Link do figma:
https://www.figma.com/file/ekLyClqr6Z2mP2iTrsKwZd/R-1000

**Comment by guih50** [comment]
endpoint get contribuentes feito por @mhme2000
