### ISSUE TITLE
Criar rota getDetails 

### ISSUE THREAD

**Issue by mhme2000** [ViniciusLuisZ/projetoSi#30]
Criar estrutura controller-service-repository para obter os detalhes de um evento enviado, provavelmente receberemos o id do evento do frontend.

Segue imagem da tela de detalhes do evento:
![image](https://user-images.githubusercontent.com/45264849/175427314-a8f142a0-0b18-4311-bacb-af3b209cdc35.png)
![image](https://user-images.githubusercontent.com/45264849/175427365-85875ab4-a4ba-4f45-886b-c44a94c642f4.png)

Segue link do protótipo no figma:
https://www.figma.com/file/ekLyClqr6Z2mP2iTrsKwZd/R-1000

**Comment by guih50** [comment]
rota get contribuente/details criada
