### ISSUE TITLE
Aqui não deveria ser um async?

### ISSUE THREAD

**Issue by guih50** [ViniciusLuisZ/projetoSi#37]
https://github.com/ViniciusLuisZ/projetoSi/blob/9172e0026d633a8a9f6358bf9caefd8baf17253c/app/infra/data/repositories/contribuinte_repository.py#L13

**Comment by mhme2000** [comment]
Então, as infos que ele está buscando, estão sendo criadas em tempo de execução. Nesse caso não existe consulta no BD

**Comment by mhme2000** [comment]
@guih50
