### ISSUE TITLE
Realizar teste de usabilidade -> criar/visualizar/atualizar/deletar softhouse

### ISSUE THREAD

**Issue by mhme2000** [ViniciusLuisZ/projetoSi#59]
Realizar o teste de integração das seguintes rotas:

[POST] softhouse
[GET] softhouse
[PUT] softhouse
[DELETE] softhouse

Anexar prints de sucesso das requisições.
Anexar prints de falha de validações como cnpj, telefone e email.
Anexar print de falhas na exclusão e busca de ids que não existem no banco de dados.

**Comment by eazevedo016** [comment]
Teste realizado.
