### ISSUE TITLE
Realizar teste de usabilidade -> criar/visualizar todos/ visualizar um/atualizar/deletar contribuinte

### ISSUE THREAD

**Issue by mhme2000** [ViniciusLuisZ/projetoSi#60]
Realizar o teste de integração das seguintes rotas:

[POST] contribuinte
[GET] contribuinte
[GET ID] contribuinte
[PUT] contribuinte
[DELETE] contribuinte

Anexar prints de sucesso das requisições.
Anexar prints de falha de validações como cnpj, telefone, email, tpInsc, classContri.
Anexar print de falhas na exclusão e busca de ids que não existem no banco de dados.

**Comment by eazevedo016** [comment]
Teste realizado.
