### ISSUE TITLE
Inserção de documentos repetidos (SOFTHOUSE)

### ISSUE THREAD

**Issue by eazevedo016** [ViniciusLuisZ/projetoSi#62]
# Problema

- Está sendo possível incluir vários documentos iguais no banco de dados. Isso gera repetição de dados.

Pra contornar é necessário verificar se o "CNPJ" já existe na base de dados antes de efetuar a inclusão. Se já existir, não deve deixar incluir.

**Comment by mhme2000** [comment]
Importante ressaltar que isso ocorre para a entidade **softhouse**.
