### ISSUE TITLE
Cadastro de Contribuinte ( POST)

### ISSUE THREAD

**Issue by eazevedo016** [ViniciusLuisZ/projetoSi#63]
# Problema

 - Quanto ao tamanho está retornando certo.
Entretanto, quando eu coloco cpf's válidos (que existem) dá internal server error. Quando coloco cpf aleatórios (que possivelmente nao existem) dá cpf inválido.

Método: POST
Rota: http://127.0.0.1:8000/contribuinte
Json utilizado:  
```JSON {
   "evtInfoContri":{
      "id":"************************************",
      "ideEvento":{
         "tpAmb":"*",
         "procEmi":"*",
         "verProc":"********************"
      },
      "ideContri":{
         "tpInsc":"*",
         "nrInsc":"**************"
      },
      "infoContri":{
         "inclusao":{
            "idePeriodo":{
               "iniValid":"*******",
               "fimValid":"*******"
            },
            "infoCadastro":{
               "clasTrib":"**",
               "indEscrituracao":"*",
               "indDesoneracao":"*",
               "indAcordoSemMulta":"*",
               "indSitPJ":"*",
               "indUniao":"*",
               "dtTransfFinsLucr":"**********",
               "dtObito":"**********",
               "contato":{
                  "nmCtt":"Teste Silva dos Santos",
                  "cpfCtt":"6679340100",
                  "foneFixo":"",
                  "foneCel":"65992697500",
                  "email":"teste@teste.com"
               },
               "softHouse":[
                  "629e6bd8376b320677695561"
               ],
               "infoEFR":{
                  "ideEFR":"*",
                  "cnpjEFR":"**************"
               }
            }
         }
      }
   }
}
```
# CPF que existe:
![image](https://user-images.githubusercontent.com/75282286/178086314-84f2a268-149a-429b-a04a-8e48e0781182.png)

# CPF que não existe:
![image](https://user-images.githubusercontent.com/75282286/178086323-1e3d8665-adcc-4a00-86d3-a9c009a49052.png)

**Comment by mhme2000** [comment]
@eazevedo016 o problema está no seguinte campo:

![image](https://user-images.githubusercontent.com/45264849/178119294-eba8d13a-3fa0-4766-965c-fb7df7c855ec.png)

Esse nrInsc deve ser um cpf ou cnpj, e como o campo não estava preenchido com números acabava dando erro de validação de cpf.
