### ISSUE TITLE
Erro com GET Contribuinte

### ISSUE THREAD

**Issue by eazevedo016** [ViniciusLuisZ/projetoSi#64]
# Problema
Método: GET
Rota:  http://127.0.0.1:8000/contribuinte/details/62a0b78dae8f25909122a538

- Está retornando esse erro ao tentar buscar um contribuinte pelo id:
![image](https://user-images.githubusercontent.com/75282286/178086551-37ba798a-c4eb-48dc-8b66-1044ff37c37e.png)

**Comment by mhme2000** [comment]
@eazevedo016 o id que é usado nesse [GET] não é o id do documento e sim o id do objeto evtInfoContri.

![image](https://user-images.githubusercontent.com/45264849/178106647-4719c91b-bd22-489e-a07a-4ccb0f71fed2.png)

![image](https://user-images.githubusercontent.com/45264849/178106698-7053df3e-bdb1-4dcc-bcfc-f8e14c1a384d.png)

**Comment by eazevedo016** [comment]
Ah entendi. Show, vou testar os demais e fechar este.
