### ISSUE TITLE
Adicionar regra de validação para o campo "classTrib"

### ISSUE THREAD

**Issue by eazevedo016** [ViniciusLuisZ/projetoSi#9]
- O campo vai consumir informações da Tabela 08 dos leiautes.
### Obs:  
Os códigos [21] e [22] somente podem ser utilizados se {tpInsc} do contribuinte for igual a  [2]. Para os demais códigos, {tpInsc} deve ser igual a [1].

**Comment by mhme2000** [comment]
![image](https://user-images.githubusercontent.com/45264849/175750670-7621cb20-0c08-4b52-bb85-cf41a54fdbdb.png)

**Comment by mhme2000** [comment]
Os dados da Tabela8 estão sendo obtidos através da função get_classContribuinte() no arquivo contribuinte_repository.py

**Comment by thevitorferreira** [comment]
feito
